[package]
name = "tumblr-likes"
version = "0.1.0"
authors = ["Alex Taylor <alex@alext.xyz>"]

[dependencies]
indicatif = "0.10.2"
reqwest = "0.9.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
toml = "0.4.9"
